# This is a config for E2B sandbox template.
# You can use template ID (0ihj8z1oro94kd0arzxp) or template name (vibe-webbuilder-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-webbuilder-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-webbuilder-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-webbuilder-test')

team_id = "3b9593ea-50c0-4d77-a982-161169f52f0a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-webbuilder-test"
template_id = "0ihj8z1oro94kd0arzxp"
